project:
  type: website

website:
  title: "ScPoProgramming"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    logo: /images/ScPo-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



