project:
  type: website

website:
  title: "ScPoProgramming"
  favicon: /images/ScPo-logo.png
  twitter-card: true
  google-analytics: "G-TQGG8QBSRH"
  body-footer: © Florian Oswald, 2023
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    logo: /images/ScPo-logo.png
    background: "#ba0202"
    foreground: "#faf7f7"

format:
  html:
    theme: journal
    linkcolor: "#ba0202"
    css: styles.css
    toc: true




