project:
  type: website

website:
  title: "ScPoProgramming"
  favicon: /images/ScPo-logo.png
  twitter-card: true
  google-analytics: "G-TQGG8QBSRH"
  body-footer: © Florian Oswald, 2023
  sidebar:
    style: "docked"
    contents:
      - section: "Lessons:"
        contents:
          - href: 01-shell-intro.qmd
            text: 1. Shell Intro
          - href: 02-filedir.qmd
            text: 2. Files and Directories
          - href: 03-filework.qmd
            text: 3. Working with Files
          - href: 04-pipes.qmd
            text: 4. Filters and Pipes
          - href: 05-git.qmd
            text: 5. Git Version Control         
          - href: https://raw.githack.com/floswald/lectures/master/04-rlang/04-rlang.html
            text: 6. R intro
          - href: https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_tidy/chapter_tidy.html#1
            text: 7. R Tidyverse
  navbar:
    left:
      - href: index.qmd
        text: Home
    logo: /images/ScPo-logo.png
    background: "#ba0202"
    foreground: "#faf7f7"
format:
  html:
    theme: journal
    linkcolor: "#ba0202"
    css: styles.css
    toc: true
    highlight-style: github







