project:
  type: website

website:
  title: "ScPoProgramming"
  favicon: /images/ScPo-logo.png
  twitter-card: true
  google-analytics: "G-TQGG8QBSRH"
  body-footer: © Florian Oswald, 2024
  sidebar:
    style: "docked"
    contents:
      - section: "Lessons:"
        contents:
          - href: 01-shell-intro.qmd
            text: 1. Shell Intro
          - href: 02-filedir.qmd
            text: 2. Files and Directories
          - href: 03-filework.qmd
            text: 3. Working with Files
          - href: 04-pipes.qmd
            text: 4. Filters and Pipes
          - href: 05-git.qmd
            text: 5. `Git` Version Control         
          - href: https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_intro_programming/chapter_intro.html
            text: 6. `R` intro
          - href: https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_tidy_programming/chapter_tidy.html
            text: 7. `R Tidyverse`
          - href: 06-concepts.qmd
            text: 8. `R` and `python` generics
          - href: https://raw.githack.com/floswald/lectures/master/05-datatable/05-datatable.html
            text: 9. `R data.table`
          - href: 09-R-packages.qmd
            text: 10. Building `R` packages
          - href: 10-spatial-R.qmd
            text: 11. Spatial Data with `R`
          - href: https://floswald.github.io/julia-bootcamp/01-variables.html
            text: 11. `julia` intro 1
          - href: https://floswald.github.io/julia-bootcamp/02-functions.html
            text: 13. `julia` intro 2

  navbar:
    left:
      - href: index.qmd
        text: Home
    logo: /images/ScPo-logo.png
    background: "#ba0202"
    foreground: "#faf7f7"
format:
  html:
    theme: journal
    linkcolor: "#ba0202"
    css: styles.css
    toc: true
    highlight-style: github







